[package]
name = "solana-runtime"
version = "1.13.5"
description = "Solana runtime"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-runtime"
edition = "2021"

[dependencies]
arrayref = "0.3.6"
bincode = "1.3.3"
blake3 = "1.3.1"
bv = { version = "0.11.1", features = ["serde"] }
bytemuck = "1.8.0"
byteorder = "1.4.3"
bzip2 = "0.4.3"
crossbeam-channel = "0.5"
dashmap = { version = "4.0.2", features = ["rayon", "raw-api"] }
dir-diff = "0.3.2"
flate2 = "1.0.22"
fnv = "1.0.7"
im = { version = "15.1.0", features = ["rayon", "serde"] }
index_list = "0.2.7"
itertools = "0.10.3"
lazy_static = "1.4.0"
log = "0.4.14"
memmap2 = "0.5.3"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
num_cpus = "1.13.1"
ouroboros = "0.14.2"
rand = "0.7.0"
rayon = "1.5.1"
regex = "1.5.4"
serde = { version = "1.0.136", features = ["rc"] }
serde_derive = "1.0.103"
solana-address-lookup-table-program = { path = "../programs/address-lookup-table", version = "=1.13.5" }
solana-bucket-map = { path = "../bucket_map", version = "=1.13.5" }
solana-compute-budget-program = { path = "../programs/compute-budget", version = "=1.13.5" }
solana-config-program = { path = "../programs/config", version = "=1.13.5" }
solana-frozen-abi = { path = "../frozen-abi", version = "=1.13.5" }
solana-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.13.5" }
solana-measure = { path = "../measure", version = "=1.13.5" }
solana-metrics = { path = "../metrics", version = "=1.13.5" }
solana-program-runtime = { path = "../program-runtime", version = "=1.13.5" }
solana-rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.13.5" }
solana-sdk = { path = "../sdk", version = "=1.13.5" }
solana-stake-program = { path = "../programs/stake", version = "=1.13.5" }
solana-vote-program = { path = "../programs/vote", version = "=1.13.5" }
solana-zk-token-proof-program = { path = "../programs/zk-token-proof", version = "=1.13.5" }
solana-zk-token-sdk = { path = "../zk-token-sdk", version = "=1.13.5" }
symlink = "0.1.0"
tar = "0.4.38"
tempfile = "3.3.0"
thiserror = "1.0"
zstd = "0.11.1"
lz4 = "1.24.0"
strum_macros = "0.24"
strum = { version = "0.24", features = ["derive"] }
spl-token = { version = "3.5.0", features = ["no-entrypoint"] }
spl-token-swap = "3.0.0"
serde_json = "1.0.79"
toml = "0.5.9"

[lib]
crate-type = ["lib"]
name = "solana_runtime"

[dev-dependencies]
assert_matches = "1.5.0"
ed25519-dalek = "=1.0.1"
libsecp256k1 = "0.6.0"
rand_chacha = "0.2.2"
solana-logger = { path = "../logger", version = "=1.13.5" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.4"
