[package]
name = "solana-storage-bigtable"
version = "1.13.5"
description = "Solana Storage BigTable"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-storage-bigtable"
edition = "2021"

[dependencies]
backoff = { version = "0.4.0", features = ["tokio"] }
bincode = "1.3.3"
bytes = "1.0"
bzip2 = "0.4.3"
enum-iterator = "0.7.0"
flate2 = "1.0.22"
futures = "0.3.26"
goauth = "0.11.1"
http = "0.2.6"
hyper = "0.14.14"
hyper-proxy = "0.9.1"
log = "0.4.14"
prost = "0.10.0"
prost-types = "0.10.0"
serde = "1.0.136"
serde_derive = "1.0.103"
smpl_jwt = "0.6.1"
solana-metrics = { path = "../metrics", version = "=1.13.5" }
solana-sdk = { path = "../sdk", version = "=1.13.5" }
solana-storage-proto = { path = "../storage-proto", version = "=1.13.5" }
solana-transaction-status = { path = "../transaction-status", version = "=1.13.5" }
thiserror = "1.0"
tokio = "1"
tonic = { version = "0.7.1", features = ["tls", "transport"] }
zstd = "0.11.1"

# openssl is a dependency of the goauth and smpl_jwt crates, but explicitly
# declare it here as well to activate the "vendored" feature that builds OpenSSL
# statically...
[target."cfg(not(windows))".dependencies]
openssl = { version = "0.10", features = ["vendored"] }
# ...except on Windows to avoid having to deal with getting CI past a build-time
# Perl dependency
[target."cfg(windows)".dependencies]
openssl = { version = "0.10", features = [] }

[lib]
crate-type = ["lib"]
name = "solana_storage_bigtable"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
